[package]
name = "ash-slug"
version = "0.1.4"
authors = ["zstar17 <zzstari17@gmail.com>"]
edition = "2024"
description = "Text data processing and organization for shader implementations of Eric Lengyel's Slug algorithm for resolution-independent vector font rendering on the GPU"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zzstar17/ash-slug"
readme = "README.md"
keywords = ["text", "graphics", "vulkan"]
categories = ["graphics", "data-structures"]
exclude = ["vulkan_shaders/"]

[dependencies]
# Renamed to not conflict with feature
ash_lib = { version = "0.38.0", optional = true, package = "ash" }
harfrust = "0.13.3"
ttf-parser = "0.25.1"

[dev-dependencies]
font-kit = "0.14.3"

[features]
"default" = ["ash"]
# Enables ash bindings
"ash" = ["ash_lib"]
